name: yuehua
version: '1.0.0'
main: com.xiaoxiaoowo.yuehua.Yuehua
api-version: '1.20'
depend: [NBTAPI]
commands:
  intogame:
    description: intogame
  markrelife:
    description: markrelife
  relife:
    description: relife
  renou:
    description: renou
  select:
    description: select
  storerelifestone:
    description: storerelifestone
  datacountget:
    description: datacountget
  dataget:
    description: dataget
  dataset:
    description: dataset
  itemdataget:
    description: itemdata
  clearup:
    description: clearup
  gi:
    description: gi
    aliases:
      - GI
      - gI
      - Gi
  mytp:
    description: mytp
  perget:
    description: perget
  setsign:
    description: setsign
  mysummon:
    description: mysummon
  arrow:
    description: arrow
  ki:
    description: ki
  money:
    description: money
  yh:
    description: yh
    aliases:
      - YH
      - yH
      - Yh
  ys:
    description: ys
    aliases:
      - YS
      - yS
      - Ys
  test:
    description: test
