name: Yuehua
version: '1.0.0'
main: org.xiaoxiao.yuehua.Yuehua
api-version: '1.20'
depend: [NBTAPI]
commands:
  clearup:
    description: clearup
  intogame:
    description: intogame
  dataget:
    description: dataget
  dataset:
    description: dataset

