name: yuehua
version: '1.0.0'
main: com.xiaoxiaoowo.yuehua.Yuehua
api-version: '1.20'
depend: [NBTAPI]
commands:
  intogame:
    description: intogame
  select:
    description: select
  dataget:
    description: dataget
  dataset:
    description: dataset
  itemdataget:
    description: itemdata
  clearup:
    description: clearup
  gi:
    description: gi
  yh:
    description: yh
  test:
    description: test
